# Generated by Django 5.1.8 on 2025-04-02 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.IntegerField(choices=[(5, 'Draft'), (10, 'Published')], default=5)),
                ('rating', models.IntegerField(choices=[(0, '0 - BAD'), (1, '1 = POOR'), (2, '2 - FAIR'), (3, '3 - GOOD'), (4, '4 - EXCELLENT'), (5, '5 - EXCEPTIONAL')], default=3)),
                ('published_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
