# Generated by Django 5.1.8 on 2025-04-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slugfild_title',
            field=models.SlugField(default='titulo-padrao', max_length=200, unique_for_date='published_ad'),
            preserve_default=False,
        ),
    ]
