# Generated by Django 5.1.8 on 2025-04-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_slugfild_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='slugfild_title',
            new_name='slugfied_title',
        ),
    ]
